const data = [

    {
      "stock_id": 1,
      "barcode_id": "Exn2323",
      "img": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      "title": "Nike Air Monarch IV",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Honda",
      "model": "City",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 2,
      "barcode_id": "A23-Gn01",
      "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      "title": "Nike Air Vapormax Plus",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 2,
      "newPrice": 200,
      "company": "Honda",
      "model": "City",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 3,
      "barcode_id": 3,
      "img": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      "title": "Nike Waffle One Sneaker",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Toyota",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 4,
      "barcode_id": 4,
      "img": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      "title": "Nike Running Shoe",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Adidas",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 5,
      "barcode_id": 5,
      "img": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
      "title": "Flat Slip On Pumps",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Vans",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "flats",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 6,
      "barcode_id": 6,
      "img": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      "title": "Knit Ballet Flat",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Adidas",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "flats",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 7,
      "barcode_id": 7,
      "img": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      "title": "Loafer flats",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Toyota",
      "model": "Camry",
      "stock_brand": "EXN",
      "category": "flats",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 8,
      "barcode_id": 8,
      "img": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
      "title": "Nike Zoom Freak",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Honda",
      "model": "Accord",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 9,
      "barcode_id": 9,
      "img": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      "title": "Nike Men's Sneaker",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Toyota",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 10,
      "barcode_id": 10,
      "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      "title": "PUMA BLACK-OCE",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 11,
      "barcode_id": 11,
      "img": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
      "title": "Pacer Future Sneaker",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "EXN",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 12,
      "barcode_id": 12,
      "img": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
      "title": "Unisex-Adult Super",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "Castrol",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 13,
      "barcode_id": 13,
      "img": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
      "title": "Roma Basic Sneaker",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "Aurora",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 14,
      "barcode_id": 14,
      "img": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
      "title": "Pacer Future Doubleknit",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "Castrol",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 15,
      "barcode_id": 15,
      "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      "title": "Fusion Evo Golf Shoe",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 100,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "KYB",
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 16,
      "barcode_id": 16,
      "img": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
      "title": "Rainbow Chex Skate",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 100,
      "company": "Vans",
      "model": "Vios",
      "stock_brand": "KYB",
      "category": "flats",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 17,
      "barcode_id": 17,
      "img": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
      "title": "Low-Top Trainers",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 100,
      "company": "Vans",
      "model": "Vios",
      "stock_brand": "KYB",
      "category": "sandals",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 18,
      "barcode_id": 18,
      "img": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
      "title": "Vans Unisex Low-Top",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 100,
      "company": "Vans",
      "model": "Vios",
      "stock_brand": "KYB",
      "category": "sandals",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 19,
      "barcode_id": 19,
      "img": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
      "title": "Classic Bandana Sneakers",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Nike",
      "model": "Accord",
      "stock_brand": "KYB",
      "category": "sandals",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 20,
      "barcode_id": 20,
      "img": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
      "title": "Chunky High Heel",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Vans",
      "model": "Vios",
      "stock_brand": "Honda",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 21,
      "barcode_id": 21,
      "img": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
      "title": "Slip On Stiletto High Heel",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 100,
      "company": "Puma",
      "model": "Vios",
      "stock_brand": "Mistubishi",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 22,
      "barcode_id": 22,
      "img": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
      "title": "DREAM PAIRS Court Shoes",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Nike",
      "model": "Accord",
      "stock_brand": "Proton",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 23,
      "barcode_id": 23,
      "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      "title": "Nike Air Vapormax Plus",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Nike",
      "model": "Accord",
      "stock_brand": null,
      "category": "sneakers",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 24,
      "barcode_id": 24,
      "img": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
      "title": "Low Mid Block Heels",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 200,
      "company": "Nike",
      "model": "Accord",
      "stock_brand": "Toyota",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 25,
      "barcode_id": 25,
      "img": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
      "title": "Chunky High Heel",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Adidas",
      "model": "Vios",
      "stock_brand": "Dummy",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 26,
      "barcode_id": 26,
      "img": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
      "title": "Amore Fashion Stilettos",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 150,
      "company": "Adidas",
      "model": "Vios",
      "stock_brand": "Dummy",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 27,
      "barcode_id": 27,
      "img": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
      "title": "Bridal Sandals Glitter",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Adidas",
      "model": "Vios",
      "stock_brand": "Dummy",
      "category": "heels",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    },
    {
      "stock_id": 28,
      "barcode_id": 28,
      "img": "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
      "title": "Wedding Prom Bridal",
      "year": 2018,
      "location": "LA-A-1",
      "stock_quantity": 10,
      "newPrice": 50,
      "company": "Adidas",
      "model": "Vios",
      "stock_brand": "Dummy",
      "category": "flats",
      "update_date": "2024-04-23T18:25:43.511Z",
      "stock_availability": 1
    }
  ]

  
export default data;
